steps:
  # Step 1: Install npm dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['install']

  # Step 2: Build the Next.js application
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'

  # Step 3: Deploy to Firebase Hosting
  # This step now uses bash to correctly expand the $FIREBASE_TOKEN environment variable.
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    entrypoint: 'bash'
    secretEnv: ['FIREBASE_TOKEN']
    args:
      - '-c'
      - |
        npm run firebase -- \
        deploy \
        --project=$$PROJECT_ID \
        --only=hosting \
        --token=$$FIREBASE_TOKEN

# Make the Firebase token available to the build steps
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/firebase-deploy-token/versions/latest
    env: 'FIREBASE_TOKEN'

# For Logging
logsBucket: 'gs://rootsnwings-build-logs-rootsnwings-465610'
