steps:
  # Step 1: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$COMMIT_SHA', '.']


  # Step 2: Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$COMMIT_SHA']

  # Step 3: Deploy the Image to Cloud Run
  # Using the modern, recommended builder for gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rootsnwings-api'
      - '--image'
      - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--service-account'
      - 'rootsnwings-firestore-accessor@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets=STRIPE_SECRET_KEY=stripe-secret:latest,RESEND_API_KEY=resend-api-key:latest'
      - '--set-env-vars=FROM_EMAIL=onboarding@resend.dev,FRONTEND_URL=http://localhost:3000,BACKEND_URL=https://rootsnwings-api-944856745086.europe-west2.run.app'

# For Logging added
logsBucket: 'gs://rootsnwings-build-logs-rootsnwings-465610'