# cloudbuild-backend.yaml
steps:
  # Step 1: Build the Docker Image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend' # Run this step inside the backend folder
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$SHORT_SHA'
      - '.'
  
  # Step 2: SonarCloud Scan (SAST)
  - name: 'sonarsource/sonar-scanner-cli:latest'
    id: 'sonar-scan'
    dir: 'backend'
    secretEnv: ['SONAR_TOKEN']
    entrypoint: 'sonar-scanner'
    args:
      - '-Dsonar.projectKey=rohanathan_rootsnwings-webapp'
      - '-Dsonar.organization=rohanathan'
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.token=$$SONAR_TOKEN'
      - '-Dsonar.sources=.'
      - '-Dsonar.python.coverage.reportPaths=coverage.xml'
  
  # Step 3: Scan Image with Trivy
  - name: 'aquasec/trivy'
    id: 'vulnerability-scan'
    args:
      - 'image'
      - '--format'
      - 'json'
      - '--severity'
      - 'CRITICAL,HIGH'
      - '--exit-code'
      - '1'
      - '--ignore-unfixed'
      - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$SHORT_SHA'
  
  # Step 4: Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/rootsnwings-repo/rootsnwings-api:$SHORT_SHA'
  
  # Step 5: GitOps Hand-off (Update config repo using yq)
  - name: 'alpine:3.19'
    id: 'update-config-repo'
    entrypoint: 'sh'
    secretEnv: ['SSH_KEY']
    args:
      - -ceu
      - |
        # Install Git, SSH, and yq
        apk add --no-cache git openssh yq
      
        # --- SSH setup ---
        mkdir -p /root/.ssh
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
      
        # Force SSH to use our injected key
        export GIT_SSH_COMMAND='ssh -i /root/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes'
      
        # --- Git identity and safety config ---
        git config --global user.email "gcp-cloud-build@${PROJECT_ID}.iam.gserviceaccount.com"
        git config --global user.name "Cloud Build"
      
        # --- Clone config repo ---
        git clone --branch "${_CONFIG_BRANCH}" --depth 1 "${_CONFIG_REPO}" /workspace/config-repo
        cd /workspace/config-repo
        git config --global --add safe.directory /workspace/config-repo
        
        # Check for the values file
        test -f "${_VALUES_PATH}" || { echo "ERROR: values file not found: ${_VALUES_PATH}"; exit 1; }
        
        # --- Update YAML (image.tag) safely with yq ---
        yq -i ".image.tag = \"$SHORT_SHA\"" "${_VALUES_PATH}"
        
        # --- Commit only if there are changes ---
        if ! git diff --quiet; then
          git add "${_VALUES_PATH}"
          git commit -m "ci: update backend image tag to $SHORT_SHA"
          git push origin "${_CONFIG_BRANCH}"
          echo "Pushed ${_VALUES_PATH} with tag $SHORT_SHA"
        else
          echo "No change in ${_VALUES_PATH}; skipping commit."
        fi

# --- Secret Manager Configuration (Required for SSH access to config repo) ---
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-ssh-key/versions/latest
    env: 'SSH_KEY'
  - versionName: projects/${PROJECT_ID}/secrets/sonar-token/versions/latest
    env: 'SONAR_TOKEN'

# Custom substitutions (must start with underscore)
substitutions:
  _CONFIG_REPO: git@github.com:rohanathan/rohanathan-rootsnwings-k8s-config.git
  _CONFIG_BRANCH: main
  _VALUES_PATH: backend/values.yaml

# Optional logging bucket
logsBucket: 'gs://rootsnwings-build-logs-rootsnwings-465610'